# Name of the workflow
name: Release

# Run on every merge or commit to the main branch
on:
  push:
    branches:
      - main

# Automatically create a GitHub Release
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
         - name: "Checkout repository"
           uses: actions/checkout@v2
           with:
            fetch-depth: 0

         - name: "Get package version"
           id: package-version
           uses: "martinbeentjes/npm-get-version-action@main"
         
             #         - uses: "aarondarwish/action-automatic-releases@lastest"
         - uses: "marvinpinto/action-automatic-releases@lastest"
           with:
             path: aarondarwish/learn-github-actions
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: ${{ steps.package-version.outputs.current-version}} 
             # run: echo ${{ steps.package-version.outputs.current-version}} 
             prerelease: false
