# Name of the workflow
name: Release

# Run on every merge or commit to the main branch
on:
  push:
    branches:
      - main

# Automatically create a GitHub Release
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
           #         - name: Show version number
           #           run: echo "${{ steps.package-json-endpoint.outputs.endpoint }}"
         - id: package-version
           uses: "martinbeentjes/npm-get-version-action@main"
         - uses: "marvinpinto/action-automatic-releases@latest"
           with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             # automatic_release_tag: ${{ steps.package-version.outputs.current-version}} 
             automatic_release_tag: latest 
             prerelease: false
