# Name of the workflow
name: Release

# Run on every merge or commit to the main branch
on:
  push:
    branches:
      - main

# Automatically create a GitHub Release
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
         - name: "Checkout repository"
           uses: actions/checkout@v2
           with:
            fetch-depth: 0
           env:
             RELEASE_TAG: "${{ github.event.release.tag_name }}"

         - name: "Get package version"
           id: package-version
           uses: "martinbeentjes/npm-get-version-action@main"
         
         - uses: "marvinpinto/action-automatic-releases@latest"
           #- uses: "aarondarwish/github-autorelease-notes@1.0.1"
           if: ${{ RELEASE_TAG == steps.package-version.outputs.current-version }}
           with:
             path: aarondarwish/learn-github-actions
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: ${{ steps.package-version.outputs.current-version}} 
             # run: echo ${{ steps.package-version.outputs.current-version}} 
             prerelease: false
