# Name of the workflow
name: Release

# Run on every merge or commit to the main branch
on:
  push:
    branches:
      - main

# Automatically create a GitHub Release
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
         - name: "Checkout repository"
           uses: actions/checkout@v2
           with:
            fetch-depth: 0
           env:
             RELEASE_TAG: "${{ github.event.release.tag_name }}"

         - name: "Get package version"
           id: package-version
           uses: "martinbeentjes/npm-get-version-action@main"

         - name: Compare the tag release value to the package.json version value
           id: compare-version
           shell: bash
           run: |
            vercompe() {
                [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
            }
            
            vercomp() {
                [ "$1" = "$2" ] && return 1 || vercompe $1 $2
            }

            echo "COMPARE_RESULT=$(vercomp ${{ github.event.release.tag_name }} ${{ steps.package-version.outputs.current-version }} && echo 1 || echo 0 )" >> $GITHUB_OUTPUT

         - name: Fail if the tag release value is equivalent to the package.json version value
           if: ${{ steps.compare-version.outputs.COMPARE_RESULT }} == 1
           shell: bash
           run: |
             echo ${{ steps.compare-version.outputs.COMPARE_RESULT }} && exit 1

         - uses: "marvinpinto/action-automatic-releases@latest"
           with:
             path: aarondarwish/learn-github-actions
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: ${{ steps.package-version.outputs.current-version}} 
             prerelease: false
